services:

  php:
    build: ./
    container_name: learning-php
    environment:
      - APACHE_RUN_USER=www-data
    working_dir: /var/www/html/
    volumes:
      - ./learn:/var/www/html
      - ./Docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "9000:9000"

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./learn:/var/www/html
      - ./Docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php