FROM php:8.2-fpm

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        nginx \
        curl \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

WORKDIR /var/www/html

COPY ./learn /var/www/html

CMD ["php-fpm"]